[program:cartoons_ai]
directory=/var/www/itd/cartoon_ai
command=/var/www/itd/cartoon_ai/venv/bin/gunicorn -c /var/www/itd/cartoon_ai/gunicorn.conf.py app:app

user=idurnev
autostart=true
autorestart=true
startsecs=10
startretries=5
stopsignal=TERM
stopasgroup=true
killasgroup=true

stdout_logfile=/var/log/supervisor/cartoons_ai.out.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
stderr_logfile=/var/log/supervisor/cartoons_ai.err.log
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=10

environment=PYTHONUNBUFFERED="1",HOME="/home/idurnev"
