"""add scene detail fields

Revision ID: 7a1fa9b298ae
Revises: 2580574d7c64
Create Date: 2026-04-15 13:26:58.263654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a1fa9b298ae'
down_revision = '2580574d7c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartoon_scenes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dialogue', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('weather', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('music', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('sound_effects', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('facial_expressions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartoon_scenes', schema=None) as batch_op:
        batch_op.drop_column('facial_expressions')
        batch_op.drop_column('sound_effects')
        batch_op.drop_column('music')
        batch_op.drop_column('weather')
        batch_op.drop_column('dialogue')

    # ### end Alembic commands ###
