"""add video fields to cartoon scenes

Revision ID: bc60a267d1d3
Revises: 7a1fa9b298ae
Create Date: 2026-04-15 13:42:12.043898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc60a267d1d3'
down_revision = '7a1fa9b298ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartoon_scenes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_prompt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('video_task_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('video_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('video_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartoon_scenes', schema=None) as batch_op:
        batch_op.drop_column('video_url')
        batch_op.drop_column('video_status')
        batch_op.drop_column('video_task_id')
        batch_op.drop_column('video_prompt')

    # ### end Alembic commands ###
